### ISSUE TITLE
Getting NO SCHEMA AVAILABLE after activating this plugin in GraphiQL Ide

### ISSUE THREAD

**Issue by dbertella** [wp-graphql/wp-graphql-woocommerce#357]
UPDATE: This is no longer an issue on v0.6.0, I'll keep it open because it might still be relevant for you, feel free to close in case.
I installed version from master v 0.6.1 downgrading to v 0.6.0 seemed to fix the issue for me

**Describe the bug**
Getting NO SCHEMA AVAILABLE after activating this plugin in GraphiQL Ide.
Everything was working fine until I activated Gql WooCommerce plugin.
Deactivating it shows the schema back

**To Reproduce**
Activate both plugins (wp-graphql and wp-graphql-woocommerce) and lookup for the schema or documentation in graphiql, both are empty

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2563196/97848711-6442f700-1ce9-11eb-9eba-bc739858fe97.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version:
WP GraphQL: 0.14.0
WooGraphQL: 0.6.1

**Additional context**

Just in case I tried to do run a query on products getting it from the documentation:
```
query MyQuery {
  products(first: 1) {
    edges {
      cursor
      node {
        id
        name
      }
    }
  }
}
```
And it responds 500
```
{
  "code": "internal_server_error",
  "message": "<p>There has been a critical error on your website.</p><p><a href=\"https://wordpress.org/support/article/debugging-in-wordpress/\">Learn more about debugging in WordPress.</a></p>",
  "data": {
    "status": 500
  },
  "additional_errors": []
}
```

**Comment by miguderp** [comment]
Most of the time when this happened to me (maybe doesn't apply to you), logging out/back on seemed to fix this issue. Maybe some important config is stored in the session/cookies and forcing it to refresh it resolves the issue.

**Comment by dbertella** [comment]
I see thanks for the response, I "fixed" it downgrading actually so maybe latest version is not super stable?
Also I noticed that in graphiql I get 500 oftens while calling the endpoint from my app works. Mystery. The problem is I don't know how to debug the wp part unfortunately. 
I will try to logout login again thanks maybe it will help, thanks

**Comment by kidunot89** [comment]
@dbertella This is due to a breaking change in WPGraphQL v0.14.0. I'll get a hotfix out as soon as I can.

**Comment by kidunot89** [comment]
@dbertella This was resolved with the release of WPGraphQL v0.15.0 and this [PR in WPGraphQL](https://github.com/wp-graphql/wp-graphql/pull/1564).

**Comment by arjunmurali1993** [comment]
Hi @kidunot89,

I'm facing the same problem in graphiql as well as getting 500 errors when querying to graphql endpoint.

WpGraphql version 1.1.8
Wp-graphql-woocommerce version 0.7.0

Once I deactivate Wp-graphql-woocommerce everything works fine. I was also able to get it working by reverting wpgraphql to version 0.14.0

On the console, I get the following errors:
```
VM182:1 POST https://my-website.com/index.php?graphql 500
(anonymous) @ VM182:1
u @ App.js:63
value @ App.js:178
_r @ react-dom.production.min.js:238
t.unstable_runWithPriority @ scheduler.production.min.js:20
_t @ react-dom.production.min.js:113
Tr @ react-dom.production.min.js:230
sr @ react-dom.production.min.js:204
Hr @ react-dom.production.min.js:263
Kr @ react-dom.production.min.js:263
(anonymous) @ react-dom.production.min.js:272
gr @ react-dom.production.min.js:208
ei @ react-dom.production.min.js:272
render @ react-dom.production.min.js:273
(anonymous) @ index.js:5
t @ bootstrap b6398cb23a41b9b84656:19
(anonymous) @ main.b7d08b5b.js:33710
t @ bootstrap b6398cb23a41b9b84656:19
(anonymous) @ bootstrap b6398cb23a41b9b84656:62
(anonymous) @ bootstrap b6398cb23a41b9b84656:62

```
```
Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: { status: 500 }
    at r (invariant.mjs:6)
    at r (buildClientSchema.mjs:27)
    at App.js:181
r @ invariant.mjs:6
r @ buildClientSchema.mjs:27
(anonymous) @ App.js:181
Promise.then (async)
value @ App.js:180
_r @ react-dom.production.min.js:238
t.unstable_runWithPriority @ scheduler.production.min.js:20
_t @ react-dom.production.min.js:113
Tr @ react-dom.production.min.js:230
sr @ react-dom.production.min.js:204
Hr @ react-dom.production.min.js:263
Kr @ react-dom.production.min.js:263
(anonymous) @ react-dom.production.min.js:272
gr @ react-dom.production.min.js:208
ei @ react-dom.production.min.js:272
render @ react-dom.production.min.js:273
(anonymous) @ index.js:5
t @ bootstrap b6398cb23a41b9b84656:19
(anonymous) @ main.b7d08b5b.js:33710
t @ bootstrap b6398cb23a41b9b84656:19
(anonymous) @ bootstrap b6398cb23a41b9b84656:62
(anonymous) @ bootstrap b6398cb23a41b9b84656:62
```

**Comment by muhaimincs** [comment]
This is still happening on WP GraphQL 1.2.6 and WooGraphQL (0.8.1) on Wordpress (5.7). Please advise @kidunot89

**Comment by DangMin** [comment]
Hi @kidunot89,

I am also having the same problem after activate the WooGraphQL, I cannot find any schema in GraphQL IDE and when I execute the query, it results wit "Internal Server Error". No other information presented ( `GRAPHQL_DEBUG` is set to true).

Once I deactivate, everything's back to normal. I am currently using Wordpress 5.7, WP-GraphQL 1.3.5 and WooGraphQL 0.8.1.

Thank you

**Comment by rndm-user** [comment]
I am currently seeing this issue with WPGraphQL 1.3.5 if Custom Post Type UI 1.9.1 plugin is enabled.
Latest version of both.

**Comment by furqan-dev4** [comment]
Facing the same issue. It works fine if CPT UI <= 1.8.2 is installed. But it does not have support for WPGraphQL.

> I am currently seeing this issue with WPGraphQL 1.3.5 if Custom Post Type UI 1.9.1 plugin is enabled.
> Latest version of both.

**Comment by erip2** [comment]
I am also currently seeing this issue with WooGraphQL 0.8.1, WP GraphQL 1.3.8, and WordPress 5.7.1.

I see this error on the console:

invariant.mjs:6 
Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: { status: 500 }
    at r (invariant.mjs:6)
    at r (buildClientSchema.mjs:27)
    at App.js:181

**Comment by HakiraAgency** [comment]
I am also not seeing any schema when i activate WooGraphQL, no problem when it's desactivated (WooGraphQL 0.8.1, WP GraphQL 1.3.8, and WordPress 5.7.2).

Should I downgrade ?

**Comment by miresk** [comment]
Hi, I also have this issue and can't see the schema @kidunot89 .

WP GraphQL : Version 1.6.1
WPGraphQL WooCommerce  : Version 0.10.2
WP v.5.8

I enabled debug mode in the settings and can't see any error messages in the IDE. I tried to log out and log in too.
Only after I run the snippet mentioned by @dbertella , there is SyntaxError: Unexpected token < in JSON at position 0

Appreciate any help or update as it seems like its a common issue. 
Thank you

**Comment by jmotes** [comment]
Thanks @miresk! I Just came here looking for a solution after updating WPGraphQL.

**Comment by wardvanzon** [comment]
When i activate the GraphQL-woocommerce plugin version 0.10.2  i get this message from Wordpress: "A critical error has occurred on this site. Check your site administrator email inbox for instructions." I used a previous version for the GraphQL-Woocommerce plugin but there would be "NO SCHEME" available.

GraphQL version: 1.6.2
GraphQL-Woocommerce version: 0.10.2, the previous version i used was 0.10.0.

**Comment by dinesh-chandak** [comment]
Yess Mee too

> When i activate the GraphQL-woocommerce plugin version 0.10.2 i get this message from Wordpress: "A critical error has occurred on this site. Check your site administrator email inbox for instructions." I used a previous version for the GraphQL-Woocommerce plugin but there would be "NO SCHEME" available.
> 
> GraphQL version: 1.6.2
> GraphQL-Woocommerce version: 0.10.2, the previous version i used was 0.10.0.

**Comment by gatoledo1** [comment]
In version 1.3.5, the same error occurred. **I solved it when exiting and logging in**.
Disabling plug-ins didn't do it, **I just logged out of my user and logged in again**.

**Comment by benjamin3105** [comment]
This error still exists:

Uncaught (in promise) Error: Invalid or incomplete introspection result. Ensure that you are passing "data" property of introspection response and no "errors" was returned alongside: { status: 500 }

And "NO SCHEME" available in GraphiQL IDE

Wordpress Version 5.9
WP GraphQL Version 1.6.12
WPGraphQL JWT Authentication Version 0.4.0
WPGraphQL for Advanced Custom Fields Version 0.5.3

Logging out/in and disabling plug-ins doesn't work.

**Comment by eliawk** [comment]
@jasonbahl 
Wordpress Version 6.0.2
WP GraphQL Version 1.11.1

<img width="379" alt="Schermata 2022-09-27 alle 21 29 16" src="https://user-images.githubusercontent.com/362016/192618174-0284b3cc-b01b-4653-a850-19b523c25f77.png">

**Comment by jasonbahl** [comment]
@eliawk can you check out the tips here: https://www.wpgraphql.com/docs/debugging/

I'd recommend inspecting the Network request and see if it has any helpful info in there

**Comment by jasonbahl** [comment]
Ah! very interesting. This feels like we could do a better job at providing a more clear warning. 🤔

**Comment by BenedictLang** [comment]
> Ah! very interesting. This feels like we could do a better job at providing a more clear warning. 🤔

Yes, would be nice. I also first suspected incompatibility issues, but it was just a mistake in my request rewrite rules.

**Comment by Mario-Boss** [comment]
hi guys.. the problem is still occurring with:
- Wordpres - version 6.8.1
- WPGraphQL - version 2.3.0
- WPGraphQL WooCommerce - version 0.19.0
No schema when the last one plugin is enabled - schema is appearing when disabled - any advice..?
